### PR TITLE
Update action.yml

### PR DESCRIPTION
**Pull request by dzervoudakes**
Update node version to remove deprecation warnings.

### CODE REVIEW

**Comment by the-wright-jamie** [comment]
I wonder if we can test just to make sure it doesn't break anything, let me see...

**Comment by the-wright-jamie** [comment]
Could you [sync your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) for me real quick please, it'll have the yml file needed to test this PR.

**Comment by dzervoudakes** [comment]
Done.

**Comment by solomonduncan** [comment]
Any update on this? Thanks for putting this together btw!

**Comment by dzervoudakes** [comment]
> Any update on this? Thanks for putting this together btw!

Thank you for resurrecting this.

@the-wright-jamie were you able to test this after I synced the fork?

**Comment by the-wright-jamie** [comment]
@dzervoudakes 

Oops, I thought I merged this. My bad! I'll take a look again tonight hopefully as I've forgotten if it's working ok or not. Apologies

**Comment by the-wright-jamie** [comment]
relates to #32

**Pull request merged**
